export type StringMap<T> = { [key: string]: T };
export type NumberMap<T> = { [key: number]: T };
export type FileEntry = {path:string,value:string};

export enum ItemType {
    "Undefined" = 0,
    "Component" = 1,
    "Device" = 2,
    "Weapon" = 3,
    "AmmunitionObsolete" = 4,
    "DroneBay" = 5,
    "Ship" = 6,
    "Satellite" = 7,
    "ShipBuild" = 8,
    "SatelliteBuild" = 9,
    "Technology" = 10,
    "ComponentStats" = 11,
    "ComponentMod" = 12,
    "Skill" = 13,
    "Faction" = 14,
    "Quest" = 15,
    "Loot" = 16,
    "Fleet" = 18,
    "Character" = 19,
    "QuestItem" = 20,
    "Ammunition" = 25,
    "VisualEffect" = 26,
    "BulletPrefab" = 27,
    "ShipSettings" = 100,
    "GalaxySettings" = 101,
    "DatabaseSettings" = 102,
    "ExplorationSettings" = 103,
}

export const ItemTypesMap = Object.freeze({
    "Undefined": 0,
    "Component": 1,
    "Device": 2,
    "Weapon": 3,
    "AmmunitionObsolete": 4,
    "DroneBay": 5,
    "Ship": 6,
    "Satellite": 7,
    "ShipBuild": 8,
    "SatelliteBuild": 9,
    "Technology": 10,
    "ComponentStats": 11,
    "ComponentMod": 12,
    "Skill": 13,
    "Faction": 14,
    "Quest": 15,
    "Loot": 16,
    "Fleet": 18,
    "Character": 19,
    "QuestItem": 20,
    "Ammunition": 25,
    "VisualEffect": 26,
    "BulletPrefab": 27,
    "ShipSettings": 100,
    "GalaxySettings": 101,
    "DatabaseSettings": 102,
    "ExplorationSettings": 103,
} as StringMap<ItemType>);

export const ItemTypesMapRev = Object.freeze({
    0: "Undefined",
    1: "Component",
    2: "Device",
    3: "Weapon",
    4: "AmmunitionObsolete",
    5: "DroneBay",
    6: "Ship",
    7: "Satellite",
    8: "ShipBuild",
    9: "SatelliteBuild",
    10: "Technology",
    11: "ComponentStats",
    12: "ComponentMod",
    13: "Skill",
    14: "Faction",
    15: "Quest",
    16: "Loot",
    18: "Fleet",
    19: "Character",
    20: "QuestItem",
    25: "Ammunition",
    26: "VisualEffect",
    27: "BulletPrefab",
    100: "ShipSettings",
    101: "GalaxySettings",
    102: "DatabaseSettings",
    103: "ExplorationSettings",
} as NumberMap<string>);

export interface DatabaseFile {
    Id: number;
    ItemType: ItemType;
}